/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ivjggbkvhbelxtzkxalb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2amdnYmt2aGJlbHh0emt4YWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NDQ5OTksImV4cCI6MjA4NzQyMDk5OX0.jg0i2QNGNzIztv4d8-_VQpq6P9s-YZdaXMuEHaYoU4E"