/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ijxiaptspjjtwblsxvvb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqeGlhcHRzcGpqdHdibHN4dnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk1MzI0NjYsImV4cCI6MjEwNTEwODQ2Nn0.yco_Ja-Xlg00VqG32SwTGF-eXg-5hrsP9ePpmk-QzFc"